### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by fededileo** [LynithDev/gnome-app-hider#13]
Hi! I don't know anything about programming although an addicted tech savvy and would like to help you translating the extension since I assume its code should be simple enough for me to understand it if you help me. Hope you like this idea :)

**Comment by LynithDev** [comment]
Will attempt to do it myself and add support for some languages using Google translate. The extension doesn't have much so it shouldn't be too much of an issue

**Comment by LynithDev** [comment]
Alright, translations added (See https://github.com/LynithDev/gnome-app-hider/pull/14/)

To add a translation, see [README.md](https://github.com/LynithDev/gnome-app-hider#translations)
