### ISSUE TITLE
AppFolder break overview page index with GNOME Version 44.4

### ISSUE THREAD

**Issue by wroyca** [LynithDev/gnome-app-hider#31]
Hello o/

An unusual bug has surfaced on my system. Specifically, if you choose to hide icons from an AppFolder, it result in overview page index breaking, accompanied by the following error message: this._pages[pageIndex] is undefined. 

This is specifically observed (again, on my system) in relation to GNOME Tour. If GNOME Tour is hidden, the bug is triggered. It is then resolved by bringing it back through the extension settings. Here's the broken layout:

![Screenshot from 2023-08-28 15-45-43](https://github.com/LynithDev/gnome-app-hider/assets/91024200/66f0293d-e977-4c76-8e1d-8ba421849bea)

And here's the layout when bringing it back:

![Screenshot from 2023-08-28 15-58-58](https://github.com/LynithDev/gnome-app-hider/assets/91024200/a4fe5d63-ce87-45ea-a935-3d72c443d689)
![Screenshot from 2023-08-28 15-59-00](https://github.com/LynithDev/gnome-app-hider/assets/91024200/80c14946-286d-48b4-a4dc-06d005c93b88)
![Screenshot from 2023-08-28 15-59-02](https://github.com/LynithDev/gnome-app-hider/assets/91024200/adb26020-dfeb-4612-90bc-89616d69cfda)

Here are some more logs:

```bash
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS ERROR: Extension app-hider@lynith.dev: TypeError: this._pages[pageIndex] is undefined
_addItemToPage@resource:///org/gnome/shell/ui/iconGrid.js:560:9
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:876:14
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:1305:29
_moveItem@resource:///org/gnome/shell/ui/appDisplay.js:1226:20
_redisplay/<@resource:///org/gnome/shell/ui/appDisplay.js:1131:22
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1121:17
_redisplay/<@resource:///org/gnome/shell/ui/appDisplay.js:1407:23
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1406:27
_patchAppView@/var/home/wroy/.local/share/gnome-shell/extensions/app-hider@lynith.dev/patches/appDisplayPatcher.js:47:53
enable@/var/home/wroy/.local/share/gnome-shell/extensions/app-hider@lynith.dev/patches/appDisplayPatcher.js:62:14
enable@/var/home/wroy/.local/share/gnome-shell/extensions/app-hider@lynith.dev/extension.js:22:32
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:196:38
async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:552:24
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:627:18
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:223:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:447:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34

JS ERROR: TypeError: this._pages[pageIndex] is undefined
_addItemToPage@resource:///org/gnome/shell/ui/iconGrid.js:560:9
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:876:14
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:1305:29
_moveItem@resource:///org/gnome/shell/ui/appDisplay.js:1226:20
_redisplay/<@resource:///org/gnome/shell/ui/appDisplay.js:1131:22
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1121:17
_redisplay/<@resource:///org/gnome/shell/ui/appDisplay.js:1407:23
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1406:27
_init/this._redisplayWorkId<@resource:///org/gnome/shell/ui/appDisplay.js:1366:18
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:802:31
_runAllDeferredWork@resource:///org/gnome/shell/ui/main.js:811:25
queueDeferredWork/_deferredTimeoutId<@resource:///org/gnome/shell/ui/main.js:895:13
```

There isn't much to work with at the moment, but let me know if there are additional avenues I can explore to provide more information.

```
Fedora Linux 38.20230828.0 (Silverblue)
GNOME Version 44.4
Wayland
Linux 6.4.12-200.fc38.x86_64
```

**Comment by LynithDev** [comment]
Hello! Thanks for reporting this, I'll look into it tomorrow as it's late for me.

**Comment by LynithDev** [comment]
Hello @wroyca! Can you clone the repo and install the extension manually to `~/.local/share/gnome-shell/extensions` and restart GNOME (logout on Wayland, `ALT+F2` and then `r` on X11) and see if it works now? Thanks!

**Comment by LynithDev** [comment]
Glad it works, that folder preview doesn't look good though lol
