### ISSUE TITLE
Apps stored in folders sorted alphabetically on every login

### ISSUE THREAD

**Issue by Pracium** [LynithDev/gnome-app-hider#32]
Hey,
since the last update all my apps stored in a folder get sorted alphabetically. Apps stored outside of folders aren't affected. Disabling this extension restores the original order.

**Normal:**
![](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/3176dce475d281499d12eb615af24437/image.png)

**With extension enabled:**
![](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/61429abec63b7e8a4ac500d08cb9f26c/Screenshot_from_2023-09-03_15-18-36.png)

I don't know if there are any logs for your extension, if so, tell me where I find them, so I can send them to you. Also, if there is anything I can help with to identify the problem, let me know.

**Comment by LynithDev** [comment]
Hello! Can you provide me a list of extensions that you have installed and enabled?

**Comment by Pracium** [comment]
Woaah. That was fast.

I only have app hider installed so it has to be your extension causing this.

**Comment by LynithDev** [comment]
Hm, strange. I guess I'd require logs

`journalctl -f -o cat /usr/bin/gnome-shell`, disable and enable the extension and tell me what happens

**Comment by Pracium** [comment]
`Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Could not issue 'GetUnit' systemd call
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
GNOME Shell started at Sun Sep 03 2023 15:54:05 GMT+0200 (Central European Summer Time)
Registering session with GDM
Shutting down GNOME Shell
Could not apply discrete GPU environment, switcheroo-control not available
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
`

Disabled and enabled the extension but there weren't any new log messages.

But I noticed I made an error in my initially post. While disabling the extension immediately restores the right order the order will stay right after enabling the extension again until i reboot or re-login.

**Comment by LynithDev** [comment]
This is really weird, I'll look into it a bit later

**Comment by LynithDev** [comment]
Could you also list your system details?

**Comment by Pracium** [comment]
![image](https://github.com/LynithDev/gnome-app-hider/assets/134810892/2758c939-e173-4648-a0ed-57fa1975fc7b)
![image](https://github.com/LynithDev/gnome-app-hider/assets/134810892/eae37371-f84d-462b-a605-6528bccc5eb8)
![image](https://github.com/LynithDev/gnome-app-hider/assets/134810892/56b9dcc6-fd3e-4273-b90c-5a9c547312b1)

Anything else you need?

**Comment by LynithDev** [comment]
No that should be all, thanks

**Comment by LynithDev** [comment]
Hey! I'd love to get around to fixing the issue but I'm a bit busy with life and other things. I'll definitely look into it this weekend, as well as the other issue.

I took a quick look about a week ago to see if it was a bug somewhere in my code, however I'm pretty sure I'll have to do a bit more looking into GNOME's shell in order to fix this

**Comment by Pracium** [comment]
Any update?

**Comment by LynithDev** [comment]
Not really, I haven't touched the extension for 3 weeks already. I have no idea how it's being caused exactly

**Comment by LynithDev** [comment]
Should be fixed in GNOME <45 with https://github.com/LynithDev/gnome-app-hider/commit/90ad268c01def37346375e78802275b0743691da
And GNOME >=45 with https://github.com/LynithDev/gnome-app-hider/commit/ee69b8ca19072657d1ef5d111b918b2799deda68
