### ISSUE TITLE
Remove Hide option from apps on the dash

### ISSUE THREAD

**Issue by CoolingTool** [LynithDev/gnome-app-hider#34]
Having the hide option doesn't make much sense since this extension only hides apps from the app menu and not the dash
![image](https://github.com/LynithDev/gnome-app-hider/assets/62089272/51497f11-0f5e-4548-9287-e2bafc107069)

Also for open apps it could be confused for the "Hide" right click option on windows which minimize the app ![image](https://github.com/LynithDev/gnome-app-hider/assets/62089272/a17db32d-076b-4c57-a4e4-8fff2142b427)

**Comment by dogo** [comment]
+1

**Comment by LynithDev** [comment]
I'll fix this issue this saturday

**Comment by LynithDev** [comment]
Fixed with https://github.com/LynithDev/gnome-app-hider/commit/0d5cb2046cd667e0c20f77ce7e7083d4fbe0fbcc for GNOME <45

Fixed with https://github.com/LynithDev/gnome-app-hider/commit/071e7e6d71270d22a853a1e5c99333c799ca3d8c for GNOME >=45
