### ISSUE TITLE
Gnome 45 Support

### ISSUE THREAD

**Issue by ilyachch** [LynithDev/gnome-app-hider#35]
Here is manual, how to move to gnome 45:

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#prefs-js

**Comment by LynithDev** [comment]
GNOME 45 support should already be available in the `gnome-45` branch, it's also available on extensions.gnome.org

**Comment by ilyachch** [comment]
Strange...

I've got error:
```
gnome-shell[3347]: JS ERROR: Extension app-hider@lynith.dev: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/misc/extensionUtils.js:4:0
```

**Comment by LynithDev** [comment]
Are you using the gnome 45 version?

**Comment by ilyachch** [comment]
Oh, sorry, my fault. Something went wrong. I've restarted session and everything works fine.
