### ISSUE TITLE
Extension stopped working after update to gnome 45

### ISSUE THREAD

**Issue by Pracium** [LynithDev/gnome-app-hider#36]
Hey,
since I updated my system to gnome 45 your extension stopped working and started showing an incompatibility message in the extension manager.

![image](https://github.com/LynithDev/gnome-app-hider/assets/134810892/b0020077-6307-41eb-9f52-a77bc542f14d)

**Comment by LynithDev** [comment]
You have to use version 14 for GNOME 45

**Comment by Pracium** [comment]
Works, thanks
