### ISSUE TITLE
GNOME 46 Support

### ISSUE THREAD

**Issue by notlet** [LynithDev/gnome-app-hider#40]
46 does not seem to introduce any breaking changes to the functionality of this extension, so it should be as simple as just adding 46 to supported versions. I'm not experienced with extension development, so I'm not sure how to do it myself, but when I disable extension version checks in dconf, App Hider works perfectly fine.

**Comment by LynithDev** [comment]
I'll see what I can do tomorrow. Thanks for letting me know
