### ISSUE TITLE
TypeError: page is undefined - Gnome 46.4 - Manjaro Linux

### ISSUE THREAD

**Issue by alouiadel** [LynithDev/gnome-app-hider#44]
Extension was working normally then it break , with error as in image below :
![image](https://github.com/user-attachments/assets/9d494eec-ac30-41b5-83fc-88be9818f605)

**Comment by LynithDev** [comment]
Hello, thanks for reporting the issue. Can you restart your machine, login and execute `journalctl -f -o cat /usr/bin/gnome-shell` in the terminal? I'd like to know what the error is exactly.

**Comment by alouiadel** [comment]
I ran dconf reset -f /org/gnome/, and the extension started working again. But when I tried hiding some apps inside a folder, it broke once more.

**Comment by LynithDev** [comment]
Can you run `journalctl -f -o cat /usr/bin/gjs`?

**Comment by alouiadel** [comment]
i have already restart and removed extension , but here : 
![image](https://github.com/user-attachments/assets/9eeec030-c3e9-40f5-a734-3410cb542254)

**Comment by alouiadel** [comment]
i am closing this , as i dont use gnome anymore
