### ISSUE TITLE
Hide apps from search

### ISSUE THREAD

**Issue by lionblaze55** [LynithDev/gnome-app-hider#7]
Not really sure what this would entail or if it is even possible, but it would be awesome to have a toggle to also have apps be hidden from the search bar in the overview!

**Comment by LynithDev** [comment]
Definitely possible. However, at that point, you should just add the `Hidden=true` option in its .desktop file.

**Comment by LynithDev** [comment]
Alright I'll see what I can do later this week

**Comment by hyuri** [comment]
Same... came here for this 👀 Cool!
